(() => {
'use strict';
const cfg=window.SITE_CONFIG||{};const shipping=window.SHIPPING_DATA||{};const CART_KEY='international_items_cart_v2';
const pageCategory=(document.body.dataset.category||'').trim();
let products=[],categories=[],view=[],cart=loadCart(),viewer={images:[],index:0};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>'L '+Number(n||0).toLocaleString('es-HN',{maximumFractionDigits:0});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function loadCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]').filter(x=>x&&x.id&&x.qty>0)}catch{return[]}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartUI();}
function cartSubtotal(){return cart.reduce((s,x)=>s+(Number(x.price)||0)*(Number(x.qty)||1),0)}
function totalQty(){return cart.reduce((s,x)=>s+(Number(x.qty)||1),0)}
function productById(id){return products.find(p=>p.id===id)}
async function init(){
  try{const [pd,cd]=await Promise.all([fetch('data/productos.json').then(r=>r.json()),fetch('data/categorias.json').then(r=>r.json())]);products=pd.products||[];categories=cd.categories||[];setupHeader();fillFilters();bind();render();updateCartUI();deepLink();}
  catch(err){console.error(err);$('#product-grid').innerHTML='<p>No se pudo cargar el catálogo. Publica la carpeta completa en GitHub Pages.</p>'}
}
function setupHeader(){const meta=categories.find(c=>c.name===pageCategory);$('#catalog-title').textContent=pageCategory||'Todos los productos';$('#catalog-description').textContent=meta?.description||'Explora todos los productos disponibles de International Items HN.';$('#category-icon').textContent=meta?.icon||'🛍️';document.title=(pageCategory||'Catálogo completo')+' | International Items HN';const wa=cfg.whatsappNumber||'50496310102';$('#floating-wa').href=`https://wa.me/${wa}?text=${encodeURIComponent('Hola, estoy viendo el catálogo de International Items.')}`;}
function fillFilters(){const sel=$('#category-filter');sel.innerHTML='<option value="">Todas las categorías</option>'+categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)} (${c.count})</option>`).join('');if(pageCategory){sel.value=pageCategory;sel.disabled=true;}}
function render(){const q=normalize($('#search-products').value);const cat=pageCategory||$('#category-filter').value;let list=products.filter(p=>(!cat||p.category===cat)&&(!q||normalize(p.name+' '+p.description.join(' ')).includes(q)));const sort=$('#sort-products').value;if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='az')list.sort((a,b)=>a.name.localeCompare(b.name,'es',{sensitivity:'base'}));view=list;$('#product-count').textContent=`${list.length} ${list.length===1?'producto':'productos'}`;$('#empty-products').hidden=!!list.length;$('#product-grid').hidden=!list.length;$('#product-grid').innerHTML=list.map(card).join('');}
function card(p){const img=p.images[0]||'';return `<article class="product-card" id="${esc(p.id)}" data-id="${esc(p.id)}"><div class="product-media"><img src="${esc(img)}" alt="${esc(p.name)}" loading="lazy" decoding="async" data-action="view"><span class="image-count">${p.images.length} foto${p.images.length===1?'':'s'}</span>${p.images.length>1?'<div class="image-nav"><button type="button" data-action="prev-image">‹</button><button type="button" data-action="next-image">›</button></div>':''}</div><div class="product-body"><span class="category-tag">${esc(p.category)}</span><h2>${esc(p.name)}</h2><p class="product-description">${esc(p.description[0]||'')}</p><div class="product-bottom"><div class="price">${money(p.price)}</div><div class="card-actions"><button class="add-cart" type="button" data-action="add">Agregar al carrito</button><button class="share-button" type="button" data-action="share" aria-label="Compartir">↗</button></div></div></div></article>`}
function bind(){
  $('#search-products').addEventListener('input',render);$('#category-filter').addEventListener('change',render);$('#sort-products').addEventListener('change',render);
  $('#product-grid').addEventListener('click',onGridClick);$('#open-cart-top').addEventListener('click',openCart);$('#floating-cart').addEventListener('click',openCart);$('#close-cart').addEventListener('click',closeCart);$('#cart-overlay').addEventListener('click',e=>{if(e.target===e.currentTarget)closeCart()});
  $('#cart-items').addEventListener('click',onCartClick);$('#checkout-button').addEventListener('click',openCheckout);$('#close-checkout').addEventListener('click',closeCheckout);$('#checkout-overlay').addEventListener('click',e=>{if(e.target===e.currentTarget)closeCheckout()});
  const f=$('#checkout-form');f.vendedor.addEventListener('change',()=>{toggleOther();fillAddresses();updateCheckoutTotals()});f.dia.addEventListener('change',toggleOther);f.direccion.addEventListener('change',updateCheckoutTotals);f.addEventListener('submit',submitOrder);
  $('#viewer-close').addEventListener('click',closeViewer);$('#viewer-prev').addEventListener('click',()=>moveViewer(-1));$('#viewer-next').addEventListener('click',()=>moveViewer(1));$('#viewer').addEventListener('click',e=>{if(e.target===e.currentTarget)closeViewer()});
  window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeViewer();closeCheckout();closeCart()}if(!$('#viewer').hidden&&e.key==='ArrowLeft')moveViewer(-1);if(!$('#viewer').hidden&&e.key==='ArrowRight')moveViewer(1)});
  window.addEventListener('message',handleBackendMessage);
}
function onGridClick(e){const card=e.target.closest('.product-card');if(!card)return;const p=productById(card.dataset.id);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='add')addToCart(p);if(action==='share')shareProduct(p);if(action==='view')openViewer(p.images,Number(card.dataset.imageIndex||0));if(action==='prev-image'||action==='next-image'){const delta=action==='next-image'?1:-1;let i=Number(card.dataset.imageIndex||0);i=(i+delta+p.images.length)%p.images.length;card.dataset.imageIndex=i;$('.product-media img',card).src=p.images[i];}}
function addToCart(p){const line=cart.find(x=>x.id===p.id);if(line)line.qty=Math.min(100,line.qty+1);else cart.push({id:p.id,name:p.name,price:p.price,image:p.images[0]||'',qty:1});saveCart();toast('Producto agregado al carrito 🛒')}
function updateCartUI(){const q=totalQty();$('#cart-count-top').textContent=q;$('#floating-cart-count').textContent=q;$('#cart-total').textContent=money(cartSubtotal());$('#cart-items').innerHTML=cart.length?cart.map(x=>`<div class="cart-line" data-id="${esc(x.id)}"><img src="${esc(x.image)}" alt=""><div><h3>${esc(x.name)}</h3><strong>${money(x.price)}</strong><div class="qty-controls"><button data-cart="minus">−</button><span>${x.qty}</span><button data-cart="plus">+</button></div></div><button class="remove-line" data-cart="remove">✕</button></div>`).join(''):'<div class="cart-empty">🛒<h3>Tu carrito está vacío</h3><p>Agrega productos desde cualquier categoría.</p></div>';$('#checkout-button').disabled=!cart.length;updateCheckoutTotals()}
function onCartClick(e){const line=e.target.closest('.cart-line');if(!line)return;const i=cart.findIndex(x=>x.id===line.dataset.id);const a=e.target.dataset.cart;if(i<0||!a)return;if(a==='plus')cart[i].qty=Math.min(100,cart[i].qty+1);if(a==='minus')cart[i].qty=Math.max(1,cart[i].qty-1);if(a==='remove')cart.splice(i,1);saveCart()}
function openCart(){$('#cart-overlay').hidden=false;document.body.classList.add('modal-open')}function closeCart(){$('#cart-overlay').hidden=true;if($('#checkout-overlay').hidden)document.body.classList.remove('modal-open')}
function openCheckout(){if(!cart.length)return;closeCart();fillAddresses();toggleOther();updateCheckoutTotals();const configured=isBackendConfigured();$('#backend-warning').hidden=configured;$('#checkout-overlay').hidden=false;document.body.classList.add('modal-open')}
function closeCheckout(){$('#checkout-overlay').hidden=true;document.body.classList.remove('modal-open')}
function toggleOther(){const f=$('#checkout-form');const so=f.vendedor.value==='Otro';$('#seller-other-wrap').hidden=!so;f.vendedor_otro.required=so;const day=f.dia.value==='Otro';$('#day-other-wrap').hidden=!day;f.dia_otro.required=day}
function addressList(){const v=$('#checkout-form').vendedor.value;return(v==='Edith'||v==='Rigo')?(shipping.EdithRigo||[]):(shipping.Mayra||[])}
function fillAddresses(){const s=$('#checkout-form').direccion;const old=s.value;s.innerHTML='<option value="">Selecciona tu colonia/sector</option>'+addressList().map(x=>`<option value="${esc(x.text)}" data-cost="${Number(x.cost)||0}">${esc(x.text)} — ${money(x.cost)}</option>`).join('');if([...s.options].some(o=>o.value===old))s.value=old}
function shippingCost(){const sub=cartSubtotal();if(sub>=Number(cfg.freeShippingThreshold||2500))return 0;const o=$('#checkout-form').direccion.selectedOptions[0];return Number(o?.dataset.cost||0)}
function updateCheckoutTotals(){if(!$('#checkout-form'))return;const sub=cartSubtotal();const has=$('#checkout-form').direccion?.value;const ship=has?shippingCost():0;$('#checkout-subtotal').textContent=money(sub);$('#checkout-shipping').textContent=has?(ship===0?'GRATIS':money(ship)):'—';$('#checkout-total').textContent=money(sub+ship)}
function isBackendConfigured(){const u=String(cfg.appsScriptUrl||'');return /^https:\/\/script\.google\.com\//.test(u)&&!u.includes('PEGAR_AQUI')}
function orderPayload(){const f=$('#checkout-form');const seller=f.vendedor.value==='Otro'?f.vendedor_otro.value.trim():f.vendedor.value;const day=f.dia.value==='Otro'?f.dia_otro.value.trim():f.dia.value;const ship=shippingCost();return {client:{nombre:f.nombre.value.trim(),telefono1:f.telefono1.value.trim(),telefono2:f.telefono2.value.trim(),dia,ubicacion:f.ubicacion.value,vendedor:seller,direccion:f.direccion.value,referencia:f.referencia.value.trim(),metodoPago:f.metodo_pago.value},items:cart.map(x=>({id:x.id,name:x.name,price:x.price,qty:x.qty,subtotal:x.price*x.qty})),subtotal:cartSubtotal(),shipping:ship,total:cartSubtotal()+ship,source:location.href,createdAt:new Date().toISOString(),website:f.website.value}}
async function submitOrder(e){e.preventDefault();const f=e.currentTarget;if(!f.reportValidity()||!cart.length)return;const payload=orderPayload();const btn=$('#submit-order');btn.disabled=true;$('#order-status').textContent='Enviando pedido…';if(!isBackendConfigured()){openWhatsApp(payload);$('#order-status').textContent='Apps Script no está configurado; abrimos WhatsApp como respaldo.';btn.disabled=false;return}try{const form=document.createElement('form');form.method='POST';form.action=cfg.appsScriptUrl;form.target='order-frame';form.hidden=true;const input=document.createElement('input');input.name='payload';input.value=JSON.stringify(payload);form.appendChild(input);document.body.appendChild(form);form.submit();form.remove();submitOrder.timer=setTimeout(()=>{btn.disabled=false;$('#order-status').textContent='El servidor tarda en responder. El carrito sigue guardado; puedes intentar nuevamente.'},20000)}catch(err){console.error(err);openWhatsApp(payload);$('#order-status').textContent='No se pudo conectar con Gmail; abrimos WhatsApp como respaldo.';btn.disabled=false}}
function handleBackendMessage(e){const d=e.data||{};if(d.type!=='INTERNATIONAL_ITEMS_ORDER')return;clearTimeout(submitOrder.timer);const btn=$('#submit-order');btn.disabled=false;if(d.ok){$('#order-status').textContent=`Pedido ${d.orderId} recibido correctamente ✅`;toast('Pedido enviado a Gmail ✅');cart=[];saveCart();$('#checkout-form').reset();setTimeout(closeCheckout,2300)}else{$('#order-status').textContent=d.message||'No se pudo registrar el pedido.'}}
function openWhatsApp(p){const items=p.items.map(x=>`- ${x.qty} × ${x.name} (${money(x.price)} c/u)`).join('\n');const msg=`🛒 *Nuevo pedido*\nCliente: ${p.client.nombre}\nTel: ${p.client.telefono1}${p.client.telefono2?' / '+p.client.telefono2:''}\nDirección: ${p.client.direccion} — ${p.client.referencia}\nDía: ${p.client.dia}\nVendedor: ${p.client.vendedor}\nPago: ${p.client.metodoPago}\n\n📦 *Productos*\n${items}\n\nSubtotal: ${money(p.subtotal)}\nEnvío: ${p.shipping===0?'GRATIS':money(p.shipping)}\n*Total: ${money(p.total)}*`;window.open(`https://wa.me/${cfg.whatsappNumber||'50496310102'}?text=${encodeURIComponent(msg)}`,'_blank')}
async function shareProduct(p){const url=`${location.origin}${location.pathname}#${p.id}`;const text=`${p.name}\n${money(p.price)}\n${url}`;try{if(navigator.share)await navigator.share({title:p.name,text,url});else{await navigator.clipboard.writeText(text);toast('Enlace copiado') }}catch(err){if(err.name!=='AbortError')toast('No se pudo compartir') }}
function openViewer(images,index=0){viewer={images,index};showViewer();$('#viewer').hidden=false;document.body.classList.add('modal-open')}function showViewer(){const img=viewer.images[viewer.index]||'';$('#viewer-image').src=img;$('#viewer-counter').textContent=`${viewer.index+1} / ${viewer.images.length}`}function moveViewer(d){if(!viewer.images.length)return;viewer.index=(viewer.index+d+viewer.images.length)%viewer.images.length;showViewer()}function closeViewer(){$('#viewer').hidden=true;if($('#cart-overlay').hidden&&$('#checkout-overlay').hidden)document.body.classList.remove('modal-open')}
function deepLink(){const id=location.hash.slice(1);if(!id)return;setTimeout(()=>{const el=document.getElementById(id);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.style.boxShadow='0 0 0 4px rgba(255,60,120,.35)';setTimeout(()=>el.style.boxShadow='',2400)}},250)}
init();
})();